--- 
- 
  hosts: digital-ocean
  pre_tasks: 
    - 
      apt: update_cache=yes
      name: "update apt cache"
    - 
      apt: "name={{item}} state=present"
      name: "install required packages"
      with_items: 
        - build-essential
        - git
        - python-pip
        - python-dev
        - libffi-dev
        - virtualenv
  tasks: 
    - 
      file: "path=/root/renjith state=touch"
      name: "Create file"
    -
      name: "create virtualenv with mysql-python installed in it"
      pip: name=raven virtualenv=/root/env_ir
    -
      name: "change permissions"
      shell: chmod 777 /root/env_ir 
    -
      name: "install dependencies into virtualenv"
      action: pip requirements=/root/requirements.txt virtualenv=/root/env_ir state=present            
  vars: 
    update_apt_cache: true
  vars_files:
    - env_vars/development.yml

  roles:
    - base
